export default {
    EXPORT: {
        CLASSIFICATION: 'Classification',
        SECTOR: 'Sector',
        VALUE: 'Value',
        SECTOR_ALLOCATION: 'Sector Allocation',
        SECTOR_ALLOCATION_INITIAL: 'Sector Allocation Initial',
        SECTOR_ALLOCATION_FINAL: 'Sector Allocation Final',
        SECTOR_ACTIVE_ALLOCATION_INITIAL: 'Sector Active Allocation Initial',
        SECTOR_ACTIVE_ALLOCATION_FINAL: 'Sector Active Allocation Final',
        TOP_10_HOLDINGS: 'Top 10 Holdings',
        INITIAL_NET: 'Initial Net',
        INITIAL_ACTIVE: 'Initial Active',
        FINAL_NET: 'Final Net',
        FINAL_ACTIVE: 'Final Active'
    },
    PORTFOLIO_TABLE: {
        ASSET_ID: 'Asset Id',
        SYMBOL: 'Symbol',
        DESCRIIPTION: 'Description',
        PRICE: 'Price',
        SHARES: 'Shares',
        VALUE: 'Value',
        UNREALIZED_GAIN_LOSS: 'UnRealized Gain/Loss',
        WEIGHT: 'Weight',
        ACTIVE_WEIGHT: 'Active Weight',
        ACTIVE_VALUE: 'Active Value',
        LOT_ID: 'Lot Id',
        BUY_DATE: 'Buy Date',
        BUY_PRICE: 'Buy Price',
        COST_BASIS: 'Cost Basis',
        TERM: 'Term',
        ORIGINAL: 'Initial',
        FINAL: 'Final',
        TRADE_LIST: 'Trade List',
        POSITIONS: 'Assets',
        TAX_LOTS: 'Lots',
        TRADED_VALUE: 'Traded Value',
        TRADED_VALUE_PERCENT: 'Traded Value Pct',
        TRADE_TYPE: 'Trade Type',
        DETAILED_TRADE_TYPE: 'Detailed Trade Type',
        REALIZED_GAIN_LOSS: 'Realized Gain/Loss',
        INITIAL_FINAL: 'Initial vs. Final',
        INITIAL_WEIGHT_PCT: 'Initial Weight Pct',
        FINAL_WEIGHT_PCT: 'Final Weight Pct',
        INITIAL_UNREALIZED_GAIN_LOSS: 'Initial UnRealized Gain/Loss',
        FINAL_UNREALIZED_GAIN_LOSS: 'Final UnRealized Gain/Loss',
        GROUP_BY: 'Group By',
        NONE: 'None',
    },
    DOWNLOAD_MENU: {
        DOWNLOAD_CSV: 'CSV',
        DOWNLOAD_EXCEL: 'Single (.xlsx)',
        DOWNLOAD_ALL_EXCEL: 'Multiple (.xlsx)',
        STRATEGY_NAME: 'Strategy',
        PORTFOLIOS: 'Portfolios',
        DOWNLOAD_WORKSPACE: 'Workspace'
    }
};