/**
 * axioma-portfolio-wealth-core
 * Portfolio Construction and Wealth Core
 *
 * OpenAPI spec version: @@version.txt
 * Contact: support@axioma.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConstraintRO } from './constraintRO';
import { HoldingsRO } from './holdingsRO';
import { Link } from './link';
import { RebalancingDefaultsRO } from './rebalancingDefaultsRO';
import { TaxCodeRO } from './taxCodeRO';
import { TaxGainLossInfoRO } from './taxGainLossInfoRO';

export interface AccountRO { 
    identity?: string;
    description?: string;
    date?: string;
    excludeFuturesFromReferenceSize?: boolean;
    referenceSize?: number;
    budgetSize?: number;
    rebalancingDefaults?: RebalancingDefaultsRO;
    taxCode?: TaxCodeRO;
    initialRealizedGainsLosses?: TaxGainLossInfoRO;
    holdings?: HoldingsRO;
    rollForward?: boolean;
    rollForwardPriceGroupName?: string;
    isCompliance?: boolean;
    constraints?: Array<ConstraintRO>;
    links?: Array<Link>;
}