/**
 * axioma-portfolio-wealth-core
 * Portfolio Construction and Wealth Core
 *
 * OpenAPI spec version: @@version.txt
 * Contact: support@axioma.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BatchAnalyticsRO } from './batchAnalyticsRO';
import { HealthScoreRO } from './healthScoreRO';
import { HoldingsRO } from './holdingsRO';
import { LogRO } from './logRO';
import { TradeRO } from './tradeRO';

export interface BatchOptimizationEntryOutputRO { 
    /**
     * Date
     */
    date?: string;
    /**
     * Status of the rebalancing solution
     */
    status?: string;
    log?: LogRO;
    /**
     * Identity of the account
     */
    accountName?: string;
    /**
     * New account flag
     */
    newAccount?: boolean;
    /**
     * Cash flow
     */
    cashFlow?: number;
    /**
     * Identity of the benchmark
     */
    benchmarkName?: string;
    /**
     * Identity of the strategy
     */
    strategyName?: string;
    /**
     * Output workspace file name.
     */
    workspaceId?: string;
    /**
     * Holdings Unit
     */
    holdingsUnit?: string;
    finalHoldings?: HoldingsRO;
    /**
     * Trade list
     */
    trades?: Array<TradeRO>;
    analytics?: BatchAnalyticsRO;
    healthInput?: HealthScoreRO;
    /**
     * Compliance flag
     */
    compliance?: boolean;
}