/**
 * axioma-portfolio-wealth-core
 * Portfolio Construction and Wealth Core
 *
 * OpenAPI spec version: @@version.txt
 * Contact: support@axioma.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Indicates whether request has been cancelled or not.
 */
export interface BatchWorkspaceArchiveFileTaskStatusROCancelled { 
    opaque?: boolean;
    acquire?: boolean;
    release?: boolean;
    plain?: boolean;
}