/**
 * axioma-portfolio-wealth-core
 * Portfolio Construction and Wealth Core
 *
 * OpenAPI spec version: @@version.txt
 * Contact: support@axioma.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LogRO } from './logRO';

export interface BatchJobRO { 
    batchId?: string;
    taskId?: number;
    batchDate?: string;
    log?: LogRO;
    status?: string;
    createdAt?: Date;
    username?: string;
    numAccounts?: number;
    numErrors?: number;
    numOptimizationsWithSolution?: number;
    numOptimizationsWithNoSolution?: number;
    strategyName?: string;
}