/**
 * axioma-portfolio-wealth-core
 * Portfolio Construction and Wealth Core
 *
 * OpenAPI spec version: @@version.txt
 * Contact: support@axioma.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BatchWorkspaceArchiveFileEntryRequestRO } from './batchWorkspaceArchiveFileEntryRequestRO';

export interface BatchWorkspaceArchiveFileRequestRO { 
    /**
     * Strategy name of the batch workspaces requested.
     */
    strategy?: string;
    /**
     * Date of the batch workspaces requested.
     */
    date?: string;
    workspaces?: Array<BatchWorkspaceArchiveFileEntryRequestRO>;
}