/**
 * axioma-portfolio-wealth-core
 * Portfolio Construction and Wealth Core
 *
 * OpenAPI spec version: @@version.txt
 * Contact: support@axioma.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExpressionRO } from './expressionRO';

export interface ConstraintSelectionRO { 
    elementType?: string;
    elementName?: string;
    multiplier?: number;
    minimum?: number;
    maximum?: number;
    minScalar?: string;
    maxScalar?: string;
    minElementType?: string;
    minElementName?: string;
    maxElementType?: string;
    maxElementName?: string;
    penalty?: number;
    penaltyScalar?: string;
    maxViolation?: number;
    maxViolationScalar?: string;
    elementPosition?: number;
    periodName?: string;
    qualificationName?: string;
    expression?: ExpressionRO;
}