/**
 * axioma-portfolio-wealth-core
 * Portfolio Construction and Wealth Core
 *
 * OpenAPI spec version: @@version.txt
 * Contact: support@axioma.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DecompositionGroupRO } from './decompositionGroupRO';
import { Link } from './link';

export interface DecompositionRO { 
    isHoldingsDecompEnabled?: boolean;
    isAlphaDecompEnabled?: boolean;
    decompositionBaseSetName?: string;
    holdingsDecompBaseName?: string;
    decompositionGroups?: Array<DecompositionGroupRO>;
    links?: Array<Link>;
}