/**
 * axioma-portfolio-wealth-core
 * Portfolio Construction and Wealth Core
 *
 * OpenAPI spec version: @@version.txt
 * Contact: support@axioma.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ExpressionRO { 
    characteristic?: string;
    combinedClassificationMetagroups?: Array<string>;
    contentBuilderGroups?: Array<string>;
    slices?: Array<Array<string>>;
    isCharacteristicMatching?: boolean;
    isCharacteristicStandAlone?: boolean;
    accountName?: string;
    benchmarkName?: string;
}