/**
 * axioma-portfolio-wealth-core
 * Portfolio Construction and Wealth Core
 *
 * OpenAPI spec version: @@version.txt
 * Contact: support@axioma.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Initial vs Final portfolio drilldown
 */
export interface InitialvsFinalAnalyticsRO { 
    /**
     * Identity of the asset
     */
    assetId?: string;
    /**
     * Description of the asset
     */
    description?: string;
    /**
     * Price of the asset
     */
    price?: number;
    /**
     * Initial Weight of the asset in the portfolio in unit Percent
     */
    initialWeightPct?: number;
    /**
     * Final Weight of the asset in the portfolio in unit Percent
     */
    finalWeightPct?: number;
    /**
     * Initial Unrealized gain/loss of the asset
     */
    initialUnRealizedGainLoss?: number;
    /**
     * Final Unrealized gain/loss of the asset
     */
    finalUnRealizedGainLoss?: number;
    /**
     * Realized gain/loss of the asset
     */
    realizedGainLoss?: number;
}