/**
 * axioma-portfolio-wealth-core
 * Portfolio Construction and Wealth Core
 *
 * OpenAPI spec version: @@version.txt
 * Contact: support@axioma.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Contains the list of errors occurred while preparing the Zip file.
 */
export interface LogRO { 
    /**
     * The list of error messages encountered while processing the request
     */
    errors?: Array<string>;
    /**
     * The list of warning messages encountered while processing the request
     */
    warnings?: Array<string>;
}