/**
 * axioma-portfolio-wealth-core
 * Portfolio Construction and Wealth Core
 *
 * OpenAPI spec version: @@version.txt
 * Contact: support@axioma.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Link } from './link';
import { ObjectiveTermValueRO } from './objectiveTermValueRO';

export interface ObjectiveRO { 
    identity?: string;
    target?: string;
    active?: boolean;
    terms?: Array<ObjectiveTermValueRO>;
    links?: Array<Link>;
}