/**
 * axioma-portfolio-wealth-core
 * Portfolio Construction and Wealth Core
 *
 * OpenAPI spec version: @@version.txt
 * Contact: support@axioma.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RebalancingOptionsRO { 
    runTimeMax?: number;
    runTimeMin?: number;
    nameCountCriterionValue?: number;
    nameCountCriterionUnit?: string;
    riskApproximation?: string;
    rightHandSideTolerance?: number;
    scaleFactor?: number;
    numberOfCores?: number;
    maxDenseCols?: number;
    useMemento?: boolean;
    relaxParam?: string;
    hierarchyToleranceValue?: number;
    hierarchyToleranceUnit?: string;
}