/**
 * axioma-portfolio-wealth-core
 * Portfolio Construction and Wealth Core
 *
 * OpenAPI spec version: @@version.txt
 * Contact: support@axioma.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountRO } from './accountRO';
import { BudgetReferenceSettingsRO } from './budgetReferenceSettingsRO';
import { RebalancingDefaultsRO } from './rebalancingDefaultsRO';
import { RebalancingOptionsRO } from './rebalancingOptionsRO';

export interface RebalancingConfigurationRO { 
    account?: AccountRO;
    strategy?: string;
    budgetReferenceSettings?: BudgetReferenceSettingsRO;
    rebalancingDefaults?: RebalancingDefaultsRO;
    rebalancingOptions?: RebalancingOptionsRO;
}