/**
 * axioma-portfolio-wealth-core
 * Portfolio Construction and Wealth Core
 *
 * OpenAPI spec version: @@version.txt
 * Contact: support@axioma.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConstraintHierarchyRO } from './constraintHierarchyRO';
import { ConstraintRO } from './constraintRO';
import { DecompositionRO } from './decompositionRO';
import { Link } from './link';
import { LocalUniverseRO } from './localUniverseRO';
import { ObjectiveRO } from './objectiveRO';
import { ObjectiveTermRO } from './objectiveTermRO';
import { StrategyOptionsRO } from './strategyOptionsRO';

export interface StrategyRO { 
    identity?: string;
    description?: string;
    date?: string;
    options?: StrategyOptionsRO;
    localUniverse?: LocalUniverseRO;
    objectives?: Array<ObjectiveRO>;
    objectiveTerms?: Array<ObjectiveTermRO>;
    constraints?: Array<ConstraintRO>;
    constraintHierarchy?: ConstraintHierarchyRO;
    decomposition?: DecompositionRO;
    links?: Array<Link>;
}