/**
 * axioma-portfolio-wealth-core
 * Portfolio Construction and Wealth Core
 *
 * OpenAPI spec version: @@version.txt
 * Contact: support@axioma.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TransactionLotAnalyticsRO } from './transactionLotAnalyticsRO';

/**
 * Trade analytics
 */
export interface TradeAnalyticsRO { 
    /**
     * Identity of the asset
     */
    assetId?: string;
    /**
     * Description of the asset
     */
    description?: string;
    /**
     * Price of the asset
     */
    price?: number;
    /**
     * Shares
     */
    shares?: number;
    /**
     * Value of the trade in currency
     */
    tradedValue?: number;
    /**
     * Value of the trade in percent
     */
    tradedValuePercent?: number;
    /**
     * BUY or SELL
     */
    tradeType?: string;
    /**
     * Detaile Trade Type
     */
    detailedTradeType?: string;
    /**
     * Trade lot types. LONG term or SHORT term or MULTIPLE (combination of long and short trades)
     */
    term?: string;
    /**
     * Realized gain/loss of the asset
     */
    realizedGainLoss?: number;
    /**
     * HoldingLot anlytics
     */
    transactionLotAnalytics?: Array<TransactionLotAnalyticsRO>;
}