/**
 * axioma-portfolio-wealth-core
 * Portfolio Construction and Wealth Core
 *
 * OpenAPI spec version: @@version.txt
 * Contact: support@axioma.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * HoldingLot anlytics
 */
export interface TransactionLotAnalyticsRO { 
    /**
     * Identity of the asset
     */
    assetId?: string;
    /**
     * Description of the asset
     */
    description?: string;
    /**
     * Lot identity
     */
    lotId?: string;
    /**
     * Buy date of the holding lot
     */
    buyDate?: string;
    /**
     * Buy price of the holding lot
     */
    buyPrice?: number;
    /**
     * Current price of the asset
     */
    price?: number;
    /**
     * Shares of the holding lot
     */
    shares?: number;
    /**
     * Value of the holding lot in currency
     */
    value?: number;
    /**
     * Cost basis of the holding lot in currency
     */
    costBasis?: number;
    /**
     * Realized gain/loss of the transaction lot
     */
    realizedGainLoss?: number;
    /**
     * Holding period of the lot. LONG term or SHORT term
     */
    term?: string;
    /**
     * BUY or SELL
     */
    tradeType?: string;
}