export default {
	PROCESSING_STATUS: {
		STRATEGY_NAME: 'Strategy Name',
		BATCH_ID: 'Batch ID',
		SUBMISSION: 'Submission',
		STATUS: 'Status',
		PORTFOLIOS: 'Portfolios',
		ERRORS: 'Errors',
		SOLUTIONS: 'Solutions',
		NO_SOLUTION: 'No Solution',
		PERCENT_COMPLETED: 'Percent Completed (%)',
		ANALYSIS_DATE: 'Analysis Date',
		MARKET_DATA_TIMESTAMP: 'Market Data Timestamp',
		START_TIME: 'Start Time',
		LAST_UPDATED_TIME: 'Last Updated Time',
		BATCH_JOB_ID: 'Batch Job ID',
		STRATGEY_ID: 'Stratgey ID',
		CREATED_BY: 'Created By',
		ERROR: 'Error',
		DATE: 'Date',
		DESCRIPTION: 'Description',
		BATCH_JOB_FAILED: 'Failed',
		BATCH_JOB_SUBMITTED: 'Submitted',
		BATCH_JOB_NOT_FOUND: 'Not Found',
		BATCH_JOB_DATA_VERIFIED: 'Verified',
		// https://docs.spring.io/spring-batch/docs/current/api/org/springframework/batch/core/BatchStatus.html
		BATCH_JOB_TASK_ABANDONED: 'Abandoned',
		BATCH_JOB_TASK_COMPLETED: 'Completed',
		BATCH_JOB_TASK_FAILED: 'Failed',
		BATCH_JOB_TASK_STARTED: 'Started',
		BATCH_JOB_TASK_STARTING: 'Starting',
		BATCH_JOB_TASK_STOPPED: 'Stopped',
		BATCH_JOB_TASK_STOPPING: 'Stopping',
		BATCH_JOB_TASK_UNKNOWN: 'Unknown',
		USERNAME: 'User'
	}
};
