export default {
	BATCH_RESULTS: {
		NO_SOLUTION: 'No Solution',
		NO_REBALANCING: 'No Rebalancing',
		DOWNLOAD_TRADE_LIST: 'Download Trade List(s) successfully',
		DOWNLOAD_WORKSPACE_FAIL:'Download workspace(s) failed for workspace id: {id}',
		DOWNLOAD_WORKSPACES: 'Download workspaces successfully submitted',
		DOWNLOAD_WORKSPACE: 'Download workspace successfully',
		ACCOUNT_NAME: 'Name',
		BENCHMARK_NAME: '@:BENCHMARK',
		STRATEGY_NAME: 'Strategy',
		PRE_ANALYTICS: 'PreAnalytics',
		POST_ANALYTICS: 'PostAnalytics',
		ACTIVE_RISK: 'Active Risk',
		TOTAL_RISK: 'Total Risk',
		CASH: 'Cash',
		TAX_LIABILITY: 'Tax Liability',
		MARKET_VALUE: 'Market Value',
		TRACKING_ERROR: 'T.E.',
		TRACKING_ERROR_DELTA: 'T.E. Δ',
		YTD_REALIZED_NET_GAIN: 'YTD Real. Net. Gain',
		YTD_REALIZED_NET_GAIN_PERCENT: 'YTD Real. Net. Gain %',
		REALIZED_NET_GAINS_DELTA: 'Δ Real. Net. Gain',
		REALIZED_NET_GAINS_DELTA_PERCENT: 'Δ Real. Net. Gain %',
		UNREALIZED_LOSS_AVAILABLE: 'Unreal. Loss. Avail.',
		UNREALIZED_LOSS_AVAILABLE_PERCENT: 'Unreal. Loss. Avail. %',
		DELTA_NET_TAX_LOSS_OVER_TRACKING_ERROR_DELTA: 'Δ Net Tax Loss/T.E.',
		NET_TAX_LOSS_OVER_TURNOVER_DELTA: 'Δ Net Tax Loss/Turnover',
		HEALTH_SCORE: 'Health Score',
		INITIAL_NUMERAIRE_CASH: 'Initial Cash Level',
		NUMERAIRE_CASH: 'Cash Level',
		NUMERAIRE_CASH_DELTA: 'Cash Level Δ',
		TURNOVER_PERCENT: 'Turnover',
		LAST_TRADE: 'Last Trade',
		RUN_DATE: 'Run Date',
		NEW_ACCOUNT: 'New Account',
		CASH_FLOW: 'Cash Flow',
		COMPLIANCE: 'Compliance',
		MARKET_VALUE_INI: 'Initial Market Value',
		NAMES_INI: 'Initial Count',
		NUMERAIRE_CASH_PCT_INI: 'Initial Cash',
		BETA_INI: 'Initial Beta',
		BETA: 'Beta',
		BETA_DELTA: 'Beta Δ',
		INITIAL_ACTIVE_BETA: 'Initial Active Beta',
		ACTIVE_BETA: 'Active Beta',
		ACTIVE_BETA_DELTA: 'Active Beta Δ',
		ACTIVE_BETA_DELTA_INI: 'Initial Active Beta Δ',
		UN_REALIZED_LOSS_AVAILABLE_PCT_INI: 'Initial Unreal. Loss. Avail.',
		UN_REALIZED_ST_LOSS_AVAILABLE_INI: 'Initial Unreal. ST Loss. Avail.',
		UN_REALIZED_ST_LOSS_AVAILABLE: 'Unreal. ST Loss. Avail.',
		UN_REALIZED_LT_LOSS_AVAILABLE_INI: 'Initial Unreal. LT Loss. Avail.',
		UN_REALIZED_LT_LOSS_AVAILABLE: 'Unreal. LT Loss. Avail.',
		TAX_LIABILITY_INI: 'Initial Tax Liability',
		REALIZED_NET_STGL_INI: 'Initial Real. Net ST G/L',
		WEALTH_LENS: 'WealthLens',
		WEALTH_LENS_DRIVER: 'WealthLens Driver',
		UNREALIZED_ST_GAINS_INI: 'Initial Unreal. ST Gains', 
		UNREALIZED_ST_GAINS: 'Unreal. ST Gains', 
		UNREALIZED_LT_GAINS_INI: 'Initial Unreal. LT Gains', 
		UNREALIZED_LT_GAINS: 'Unreal. LT Gains', 
		REALIZED_ST_GAINS_YTD_INI: 'Initial YTD Real. ST Gains', 
		REALIZED_ST_GAINS_YTD: 'YTD Real. ST Gains', 
		REALIZED_ST_GAINS_YTD_DELTA: 'YTD Real. ST Gains Δ', 
		REALIZED_ST_LOSSES_YTD_INI: 'Initial YTD Real. ST Losses', 
		REALIZED_ST_LOSSES_YTD: 'YTD Real. ST Losses', 
		REALIZED_ST_LOSSES_YTD_DELTA: 'YTD Real. ST Losses Δ', 
		REALIZED_LT_GAINS_YTD_INI: 'Initial YTD Real. LT Gains', 
		REALIZED_LT_GAINS_YTD: 'YTD Real. LT Gains', 
		REALIZED_LT_GAINS_YTD_DELTA: 'YTD Real. LT Gains Δ', 
		REALIZED_LT_LOSSES_YTD_INI: 'Initial YTD Real. LT Losses', 
		REALIZED_LT_LOSSES_YTD: 'YTD Real. LT Losses', 
		REALIZED_LT_LOSSES_YTD_DELTA: 'YTD Real. LT Losses Δ',
		COMPLIANCE_RULES_APPLIED: 'Compliance Rules Applied',
	},
	WEALTH_LENS: 'WealthLens',
	STRATEGY_NAME: 'Strategy',
	AS_OF: 'As of',
	SECTOR_ALLOCATION:'Sector Allocation',
	SECTOR_ALLOCATION_EXPOSURES:'Sector Allocation (Exposures)',
	PORTFOLIO_NAME: 'Portfolio Name',
	FINAL_MARKET_VALUE: 'Final Market Value'
};
